### ISSUE TITLE
Decryption failed. Invalid router backup file.

### ISSUE THREAD

**Issue by mrtaxi** [electronicayciencia/tr-069-proxy#1]
Hi!
Cant decrypt device.cfg - Decryption failed. Invalid router backup file.
I tried to  decrypt testfile, but have the same issue.

**Comment by electronicayciencia** [comment]
Hello. What can I do?

**Comment by electronicayciencia** [comment]
Insufficient information. Closed.

**Comment by dacabemo** [comment]
Hello! For a next level and investigation I will try to. Thank you so much for this fantastic study and also your website, it’s so instructive and interesant. Please, continue showing people all these things. Best regards
