### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by quarkpower** [electronicayciencia/tr-069-proxy#2]
Tried today with fw ver SGDV10000059 and it doesn't decode the cfg file

**Comment by DervishD** [comment]
Apparently the password has changed. I don't have the tools to redo the work, so I can only bruteforce the password, which is not feasible.

I'm using SGDV10000059, too. It's the new router forced upon me from the fibre provider (my real provider does not have fibre in my area) and I want to decode the config just in case I want to modify something without going through the pain of the horrid web interface.

**Comment by quarkpower** [comment]
ploam/gpon isn't shown at the cfg file, isn't it?

**Comment by DervishD** [comment]
No idea, sorry 🤷🏼‍♂️ In my case, I once had success getting the IDONT by calling customer service for my provider, and they asked me if I needed the PLOAM too, but I did not so I never tried.

**Comment by quarkpower** [comment]
is it masmovil or pepephone?

**Comment by electronicayciencia** [comment]
Sagemcom updated the firmware shortly after I release this script. They changed the encryption algorithm. So it only works in legacy firmwares (before October 2021).

**Comment by DervishD** [comment]
> is it masmovil or pepephone?

Pepephone, switched from a NEBA to Jazztel node, but this is hijacking the closed issue, so let's move the conversation elsewhere 😉 

> Sagemcom updated the firmware shortly after I release this script. They changed the encryption algorithm. So it only works in legacy firmwares (before October 2021).

Thanks @electronicayciencia and also thanks for the detailed instructions. I bet the new encryption system is also based in security through obscurity, making difficult for end users to tweak configuration while at the same time giving no protection against people wanting to hack the router.

Anyway, thanks a lot and my excuses for hijacking the bug report 👼🏼
