### ISSUE TITLE
Sagemcom 5670 Invalid router backup file

### ISSUE THREAD

**Issue by jcastro** [electronicayciencia/tr-069-proxy#3]
Hi! I just got installed a Sagemcom 5670 but looks like the tool is not working with that router? I'm getting:

"Decryption failed. Invalid router backup file." - I saved the backup file using 1234 user, as I don't have access to admin user

Not sure if I'm doing something wrong or if something has changed on the 5670 version. Thanks for any info and great work and tool!

EDIT: Router was provided by Yoigo

**Comment by electronicayciencia** [comment]
They released a new firmware version shortly after the release of this script. It no longer works.
