### ISSUE TITLE
showconfig.exe incompatible with Windows 10 Pro

### ISSUE THREAD

**Issue by julienlag** [electronicayciencia/tr-069-proxy#4]
Hola, 
the showconfig.exe program seems to be incompatible with Windows 10 Pro:
```
showconfig.exe ..\device.cfg
This version of showconfig.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```
Is there a trick to make it work? Any similar reports from other users?
I've also tried the following in Linux:
```
./showconfig.py ../../../somos_conexion_router_F\@st\ 5657_092022.cfg 
Decryption failed. Invalid router backup file.
```
I guess it's because the backup file is from a recent firmware.

Any help would be very much appreciated! Thank you very much!!

**Comment by electronicayciencia** [comment]
Hello Julien.

I have no similar reports from other users. Have you tried compatibility settings?

You're correct. Decryption fails in recent firmware files. They must have changed the key or the algorithm.

Regards.
